### ISSUE TITLE
Hubot 3.x compatibility

### ISSUE THREAD

**Issue by herz0g** [sparksterz/hubot-tableflip#1]
With Hubot 3.x I get this error:

`Feb 28 07:44:18 hubot systemd-resolved[332]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Feb 28 07:44:18 hubot systemd-resolved[332]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Feb 28 07:44:18 hubot hubot[8059]: [Thu Feb 28 2019 07:44:18 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'gif' of null
Feb 28 07:44:18 hubot hubot[8059]:   at /home/bamboo/slack-hubot/node_modules/hubot-tableflip/src/tableflip.coffee:18:9, <js>:5:41
Feb 28 07:44:18 hubot hubot[8059]:   at ClientRequest.<anonymous> (/home/bamboo/slack-hubot/node_modules/scoped-http-client/src/index.js:99:20)
Feb 28 07:44:18 hubot hubot[8059]:   at emitOne (events.js:116:13)
Feb 28 07:44:18 hubot hubot[8059]:   at ClientRequest.emit (events.js:211:7)
Feb 28 07:44:18 hubot hubot[8059]:   at Socket.socketErrorListener (_http_client.js:387:9)
Feb 28 07:44:18 hubot hubot[8059]:   at emitOne (events.js:116:13)
Feb 28 07:44:18 hubot hubot[8059]:   at Socket.emit (events.js:211:7)
Feb 28 07:44:18 hubot hubot[8059]:   at emitErrorNT (internal/streams/destroy.js:64:8)
Feb 28 07:44:18 hubot hubot[8059]:   at _combinedTickCallback (internal/process/next_tick.js:138:11)
Feb 28 07:44:18 hubot hubot[8059]:   at process._tickCallback (internal/process/next_tick.js:180:9)
Feb 28 07:44:18 hubot hubot[8059]: [Thu Feb 28 2019 07:44:18 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'gif' of null
Feb 28 07:44:18 hubot hubot[8059]:   at /home/bamboo/slack-hubot/node_modules/hubot-tableflip/src/tableflip.coffee:18:9, <js>:5:41
Feb 28 07:44:18 hubot hubot[8059]:   at ClientRequest.<anonymous> (/home/bamboo/slack-hubot/node_modules/scoped-http-client/src/index.js:99:20)
Feb 28 07:44:18 hubot hubot[8059]:   at emitOne (events.js:116:13)
Feb 28 07:44:18 hubot hubot[8059]:   at ClientRequest.emit (events.js:211:7)
Feb 28 07:44:18 hubot hubot[8059]:   at Socket.socketCloseListener (_http_client.js:363:9)
Feb 28 07:44:18 hubot hubot[8059]:   at emitOne (events.js:121:20)
Feb 28 07:44:18 hubot hubot[8059]:   at Socket.emit (events.js:211:7)
Feb 28 07:44:18 hubot hubot[8059]:   at TCP._handle.close [as _onclose] (net.js:567:12)`

**Comment by sparksterz** [comment]
Hmm...yeah it's having issues for me too (admittedly I haven't looked at this in a while >.>). It appears some of these don't like resolving that URL. At first glance it looks like a dns resolution issue that is resolved with adding `www` into the URL chain. I'll give that a shot push it to my bot.

**Comment by herz0g** [comment]
I have fixed it by my own but actually I only get a link as answer from hubot through the slack adapter.

```
module.exports = (robot) ->

# robot.respond /flip/i, (res) ->
 robot.hear /flip/i, (msg) ->
  robot.http("http://www.tableflipper.com/json")
    .header('Accept', 'application/json')
    .get() (err, response, body) ->
      # error checking code here

#      data = JSON.parse body
#      res.send "#{data.gif}"
      msg.send JSON.parse(body).gif
```

Any idea how to send the image directly instead of the url ?

**Comment by sparksterz** [comment]
I've updated it as of version 0.1.2 if you'd like it. It appears the link from the json api also omits "www" so when the api responds with the link slack wasn't able to resolve the link either.

As for sending the image directly, I didn't want to go to that level as for free Slack teams it would add to their uploaded file size limit. Linking in this case was more desirable. Looking at the Slack API however it seems rather than sending as a message, you can send as an attachment (though I believe that still relies on a link url), or there is a files.upload api command that can do a bit more in that regard, but the file would likely need downloading in memory and re-served via that api.

**Comment by sparksterz** [comment]
Your code should work, but you'll have the same issue I ran into as of version 0.1.1
If the link resolves correctly Slack should try to retrieve it and automatically add the image for you.

**Comment by herz0g** [comment]
Your new Code is not working for me:

```
module.exports = (robot) ->
        robot.hear /tableflip/i, (msg) ->
                msg.http("http://www.tableflipper.com/json")
                .get() (err, res, body) ->
                msg.send 'http://www.tableflipper.com/'+JSON.parse(body).gif.split('/')[3]
```

I get this error, when I trigger the bot with tableflip:

```
Feb 28 11:41:17 hubot hubot[9636]: [Thu Feb 28 2019 11:41:17 GMT+0100 (CET)] ERROR ReferenceError: body is not defined
Feb 28 11:41:17 hubot hubot[9636]:   at TextListener.callback (/home/bamboo/slack-hubot/scripts/tableflip.coffee:34:12, <js>:5:67)
Feb 28 11:41:17 hubot hubot[9636]:   at executeListener (/home/bamboo/slack-hubot/node_modules/hubot/src/listener.js:79:16)
Feb 28 11:41:17 hubot hubot[9636]:   at allDone (/home/bamboo/slack-hubot/node_modules/hubot/src/middleware.js:56:7)
Feb 28 11:41:17 hubot hubot[9636]:   at /home/bamboo/slack-hubot/node_modules/async/lib/async.js:274:13
Feb 28 11:41:17 hubot hubot[9636]:   at Object.async.eachSeries (/home/bamboo/slack-hubot/node_modules/async/lib/async.js:142:20)
Feb 28 11:41:17 hubot hubot[9636]:   at async.reduce (/home/bamboo/slack-hubot/node_modules/async/lib/async.js:268:15)
Feb 28 11:41:17 hubot hubot[9636]:   at _combinedTickCallback (internal/process/next_tick.js:131:7)
Feb 28 11:41:17 hubot hubot[9636]:   at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by herz0g** [comment]
Works now, no clue why it wasn't before. Thanks for your help.
```

module.exports = (robot) ->

 robot.hear /tableflip/i, (msg) ->
  robot.http("http://www.tableflipper.com/json")
    .header('Accept', 'application/json')
    .get() (err, response, body) ->
      # error checking code here

      msg.send 'http://www.tableflipper.com/'+JSON.parse(body).gif.split('/')[3]
```

**Comment by sparksterz** [comment]
No problem. It could be a difference between Hubot 2.x and 3.x I'm not sure. Hadn't touched this code base in about 3 years before today. My hubot is still on 2.x

Your code seems to call the url via robot.http versus mine which uses msg.http I'm guessing mine is an old no longer supported pattern. Maybe some day I'll get around to updating it, but admittedly I don't really use my slackbot much anymore.
